### ISSUE TITLE
'Channel not allowed' when sending requests

### ISSUE THREAD

**Issue by IaZ001** [shayaantx/botdarr#110]
Hello,

I have just installed Botdarr using Docker Compose. My environment variables seem to be correct, but when I try to send commands to the channel, such as '!Help', I receive this message: '2023-Jul-04 11:10:52 AM [pool-5-thread-1] WARN TelegramLog - Channel test not allowed, check properties file'

Can you help me resolve this issue?

**Comment by shayaantx** [comment]
@IaZ001 can you post your compose file with secrets omitted?

**Comment by IaZ001** [comment]
> @IaZ001 can you post your compose file with secrets omitted?

Yeah for sure 

`version: "3.8"
networks:
  dacave:
    driver: bridge

services:
 #Radarr
  radarr:
    platform: linux/x86_64
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - dacave
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Indian/Mayotte
    volumes:
      - ./radarr/config:/config
      - type: bind
        source: /mnt/media
        target: /torrent

    ports:
      - 7878:7878
    restart: unless-stopped

  #Sonarr
  Sonarr:
    platform: linux/x86_64
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./sonarr/config:/config
      - type: bind
        source: /mnt/media
        target: /torrent
    networks:
      - dacave
    environment:
        PUID: 1000
        PGID: 1000
        TZ: Indian/Mayotte
    ports:
        - 8989:8989
    restart: unless-stopped
    
  # Telegram bot
  botdarr:
    image: shayaantx/botdarr:latest
    container_name: botdarr
    environment:
      # telegramm settings 
      TELEGRAM_TOKEN	: BOT TOKEN
      TELEGRAM_PRIVATE_CHANNELS	: https://t.me/ID
      # Radarr
      RADARR_URL: http://192.168.1.202:7878
      RADARR_TOKEN: TOKEN
      RADARR_DEFAULT_PROFILE: HD - 720p/1080p
      # Sonarr
      SONARR_URL: http://192.168.1.202:8989
      SONARR_TOKEN: TOKEN
      SONARR_DEFAULT_PROFILE: Any
      TZ: Indian/Mayotte
    volumes:
       - ./botdarr/logs:/home/botdarr/logs
       - ./botdarr/database:/home/botdarr/database `

**Comment by shayaantx** [comment]
If you follow https://github.com/shayaantx/botdarr/wiki/Install-Telegram-Bot

![image](https://github.com/shayaantx/botdarr/assets/5449086/c88be90a-b0a9-414f-aa42-5149160397a9)

Your telegram private channel setting is using a url, channel ids are not urls, they are the number in the url

https://t.me/c/1156742262/2

1156742262 => channel id

**Comment by IaZ001** [comment]
For sure 
```
version: "3.8"
networks:
  dacave:
    driver: bridge

services:
 #Radarr
  radarr:
    platform: linux/x86_64
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - dacave
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Indian/Mayotte
    volumes:
      - ./radarr/config:/config
      - type: bind
        source: /mnt/media
        target: /torrent

    ports:
      - 7878:7878
    restart: unless-stopped

  #Sonarr
  Sonarr:
    platform: linux/x86_64
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./sonarr/config:/config
      - type: bind
        source: /mnt/media
        target: /torrent
    networks:
      - dacave
    environment:
        PUID: 1000
        PGID: 1000
        TZ: Indian/Mayotte
    ports:
        - 8989:8989
    restart: unless-stopped
    
  # Telegram bot
  botdarr:
    image: shayaantx/botdarr:latest
    container_name: botdarr
    environment:
      # telegramm settings 
      TELEGRAM_TOKEN	: BOT TOKEN
      TELEGRAM_PRIVATE_CHANNELS	: https://t.me/ID
      # Radarr
      RADARR_URL: http://IP:7878
      RADARR_TOKEN: TOKEN
      RADARR_DEFAULT_PROFILE: HD - 720p/1080p
      # Sonarr
      SONARR_URL: http://IP:8989
      SONARR_TOKEN: TOKEN
      SONARR_DEFAULT_PROFILE: Any
      TZ: Indian/Mayotte
    volumes:
       - ./botdarr/logs:/home/botdarr/logs
       - ./botdarr/database:/home/botdarr/database 
```
