### ISSUE TITLE
Bot Spamming: Requested failed with exception, e=null,class=class java.lang.NullPointerException

### ISSUE THREAD

**Issue by daedric7** [shayaantx/botdarr#111]
Out of nowhere the bot is spamming the Matrix room every 5 minutes with:

`Requested failed with exception, e=null,class=class java.lang.NullPointerException`

In red.

No errors on the docker logs, still replies to !help

![image](https://github.com/shayaantx/botdarr/assets/4562461/c1ba6936-97f1-4be0-a98b-8ee4340c1899)

How can i debug this further ??

Docker compose:
```
services:
    botdarr:
        image: shayaantx/botdarr:latest
        container_name: botdarr
```

I have Lidarr, Radarr and Sonarr(v3), as well as Matrix settings.
