### ISSUE TITLE
com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2

### ISSUE THREAD

**Issue by daedric7** [shayaantx/botdarr#114]
Recently after a server migration, i've been getting errors both in the logs as well as Matrix room.

```
botdarr  | 2023-Dec-13 09:00:23 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:02:23 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:04:23 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:06:24 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:08:24 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:10:24 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:12:24 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:14:24 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:16:25 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:18:25 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:20:25 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:22:28 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:24:28 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:26:28 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:28:28 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
botdarr  | 2023-Dec-13 09:30:29 AM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2

```

![image](https://github.com/shayaantx/botdarr/assets/4562461/9c1cede2-a6b4-4bd1-bbf0-4cd8e797eff8)

It seems the bot cannot find Sonarr (V4) info:

![image](https://github.com/shayaantx/botdarr/assets/4562461/a76c1f33-6b72-4e64-b06b-c811c3435000)

Sonarr's profiles are the standard:

![image](https://github.com/shayaantx/botdarr/assets/4562461/f1bc44af-85cf-4780-b49f-951b839b59e7)

How can i help further debug this ?

**Comment by shayaantx** [comment]
@daedric7 can you zip the logs and provide the config for your container?

**Comment by daedric7** [comment]
Sure:

[logs.tar.gz](https://github.com/shayaantx/botdarr/files/13672215/logs.tar.gz)

```

services:
    botdarr:
        image: shayaantx/botdarr:latest
        container_name: botdarr
        environment:
           RADARR_URL: https://radarr.domain.com
           RADARR_TOKEN: API
           RADARR_DEFAULT_PROFILE: Any
           RADARR_PATH: /share/media/jellyfin/movies
           SONARR_URL: https://sonarr.domain.com
           SONARR_TOKEN: API
           SONARR_DEFAULT_PROFILE: Any
           SONARR_PATH: /share/media/jellyfin/tvshows
           SONARR_V4: yes
           LIDARR_URL: https://lidarr.domain.com
           LIDARR_TOKEN: API
           LIDARR_DEFAULT_QUALITY_PROFILE: Any
           LIDARR_DEFAULT_METADATA_PROFILE: Standard
           LIDARR_PATH: /share/media/music
           MATRIX_USERNAME: user
           MATRIX_PASSWORD: password
           MATRIX_ROOM: "!room:matrix.org"
           MATRIX_HOME_SERVER_URL: "https://domain.com"
        volumes:
           - ./logs:/home/botdarr/logs
           - ./database:/home/botdarr/database
           - /share/media:/share/media
```
